    { "L"          , OPT_EXIT, {(void*) show_license},      "show license" },
    { "h"          , OPT_EXIT, { (void*)show_help},         "show help", "topic" },
    { "?"          , OPT_EXIT, { (void*)show_help},         "show help", "topic" },
    { "help"       , OPT_EXIT, { (void*)show_help},         "show help", "topic" },
    { "-help"      , OPT_EXIT, { (void*)show_help},         "show help", "topic" },
    { "version"    , OPT_EXIT, { (void*)show_version},      "show version" },
    { "formats"    , OPT_EXIT, { (void*)show_formats  },    "show available formats" },
    { "codecs"     , OPT_EXIT, { (void*)show_codecs   },    "show available codecs" },
    { "decoders"   , OPT_EXIT, { (void*)show_decoders },    "show available decoders" },
    { "encoders"   , OPT_EXIT, { (void*)show_encoders },    "show available encoders" },
    { "bsfs"       , OPT_EXIT, { (void*)show_bsfs     },    "show available bit stream filters" },
    { "protocols"  , OPT_EXIT, { (void*)show_protocols},    "show available protocols" },
    { "filters"    , OPT_EXIT, { (void*)show_filters  },    "show available filters" },
    { "pix_fmts"   , OPT_EXIT, { (void*)show_pix_fmts },    "show available pixel formats" },
    { "layouts"    , OPT_EXIT, { (void*)show_layouts  },    "show standard channel layouts" },
    { "sample_fmts", OPT_EXIT, { (void*)show_sample_fmts }, "show available audio sample formats" },
    { "loglevel"   , HAS_ARG,  { (void*)opt_loglevel},      "set libav* logging level", "loglevel" },
    { "v",           HAS_ARG,  { (void*)opt_loglevel},      "set libav* logging level", "loglevel" },
    { "debug"      , HAS_ARG,  { (void*)opt_codec_debug},   "set debug flags", "flags" },
    { "fdebug"     , HAS_ARG,  {(void*) opt_codec_debug},   "set debug flags", "flags" },
    { "report"     , 0,        {(void*)opt_report}, "generate a report" },
    { "max_alloc"  , HAS_ARG,  {(void*) opt_max_alloc},     "set maximum size of a single allocated block", "bytes" },
    { "cpuflags"   , HAS_ARG | OPT_EXPERT, {(void*) opt_cpuflags}, "force specific cpu flags", "flags" },
